import 'package:epic_blocks/features/blocks/domain/block_position.dart';
import 'package:epic_blocks/features/blocks/domain/block_shape.dart';
import 'package:flutter/material.dart';

/// Catalog of available EpicBlocks shapes.
class BlockShapes {
  const BlockShapes._();

  /// Full 1010-like shape catalog.
  static const all = <BlockShape>[
    BlockShape(
      id: 'single',
      label: 'Single block',
      cells: [BlockPosition(0, 0)],
      lightColor: Color(0xFF2563EB),
      darkColor: Color(0xFF60A5FA),
    ),
    BlockShape(
      id: 'bar_2_h',
      label: 'Two horizontal',
      cells: [BlockPosition(0, 0), BlockPosition(0, 1)],
      lightColor: Color(0xFF059669),
      darkColor: Color(0xFF34D399),
    ),
    BlockShape(
      id: 'bar_2_v',
      label: 'Two vertical',
      cells: [BlockPosition(0, 0), BlockPosition(1, 0)],
      lightColor: Color(0xFF047857),
      darkColor: Color(0xFF6EE7B7),
    ),
    BlockShape(
      id: 'bar_3_h',
      label: 'Three horizontal',
      cells: [BlockPosition(0, 0), BlockPosition(0, 1), BlockPosition(0, 2)],
      lightColor: Color(0xFFDC2626),
      darkColor: Color(0xFFF87171),
    ),
    BlockShape(
      id: 'bar_3_v',
      label: 'Three vertical',
      cells: [BlockPosition(0, 0), BlockPosition(1, 0), BlockPosition(2, 0)],
      lightColor: Color(0xFFB91C1C),
      darkColor: Color(0xFFFCA5A5),
    ),
    BlockShape(
      id: 'bar_4_h',
      label: 'Four horizontal',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(0, 3),
      ],
      lightColor: Color(0xFF9333EA),
      darkColor: Color(0xFFC084FC),
    ),
    BlockShape(
      id: 'bar_4_v',
      label: 'Four vertical',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(1, 0),
        BlockPosition(2, 0),
        BlockPosition(3, 0),
      ],
      lightColor: Color(0xFF7E22CE),
      darkColor: Color(0xFFD8B4FE),
    ),
    BlockShape(
      id: 'bar_5_h',
      label: 'Five horizontal',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(0, 3),
        BlockPosition(0, 4),
      ],
      lightColor: Color(0xFFEA580C),
      darkColor: Color(0xFFFB923C),
    ),
    BlockShape(
      id: 'bar_5_v',
      label: 'Five vertical',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(1, 0),
        BlockPosition(2, 0),
        BlockPosition(3, 0),
        BlockPosition(4, 0),
      ],
      lightColor: Color(0xFFC2410C),
      darkColor: Color(0xFFFDBA74),
    ),
    BlockShape(
      id: 'square_2',
      label: 'Two by two square',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
      ],
      lightColor: Color(0xFF0891B2),
      darkColor: Color(0xFF67E8F9),
    ),
    BlockShape(
      id: 'square_3',
      label: 'Three by three square',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(1, 2),
        BlockPosition(2, 0),
        BlockPosition(2, 1),
        BlockPosition(2, 2),
      ],
      lightColor: Color(0xFF0D9488),
      darkColor: Color(0xFF5EEAD4),
    ),
    BlockShape(
      id: 'corner_tl',
      label: 'Corner top left',
      cells: [BlockPosition(0, 0), BlockPosition(1, 0), BlockPosition(1, 1)],
      lightColor: Color(0xFFE11D48),
      darkColor: Color(0xFFFB7185),
    ),
    BlockShape(
      id: 'corner_tr',
      label: 'Corner top right',
      cells: [BlockPosition(0, 1), BlockPosition(1, 0), BlockPosition(1, 1)],
      lightColor: Color(0xFFBE123C),
      darkColor: Color(0xFFFFA3B5),
    ),
    BlockShape(
      id: 'corner_bl',
      label: 'Corner bottom left',
      cells: [BlockPosition(0, 0), BlockPosition(0, 1), BlockPosition(1, 0)],
      lightColor: Color(0xFFDB2777),
      darkColor: Color(0xFFF9A8D4),
    ),
    BlockShape(
      id: 'corner_br',
      label: 'Corner bottom right',
      cells: [BlockPosition(0, 0), BlockPosition(0, 1), BlockPosition(1, 1)],
      lightColor: Color(0xFFC026D3),
      darkColor: Color(0xFFF0ABFC),
    ),
    BlockShape(
      id: 'l_4_down_right',
      label: 'Large L down right',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(1, 0),
        BlockPosition(2, 0),
        BlockPosition(2, 1),
      ],
      lightColor: Color(0xFF4F46E5),
      darkColor: Color(0xFFA5B4FC),
    ),
    BlockShape(
      id: 'l_4_down_left',
      label: 'Large L down left',
      cells: [
        BlockPosition(0, 1),
        BlockPosition(1, 1),
        BlockPosition(2, 0),
        BlockPosition(2, 1),
      ],
      lightColor: Color(0xFF4338CA),
      darkColor: Color(0xFFC7D2FE),
    ),
    BlockShape(
      id: 'l_4_right_down',
      label: 'Large L right down',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(1, 0),
      ],
      lightColor: Color(0xFF1D4ED8),
      darkColor: Color(0xFF93C5FD),
    ),
    BlockShape(
      id: 'l_4_right_up',
      label: 'Large L right up',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(1, 2),
      ],
      lightColor: Color(0xFF1E40AF),
      darkColor: Color(0xFFBFDBFE),
    ),
    BlockShape(
      id: 't_up',
      label: 'T up',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(1, 1),
      ],
      lightColor: Color(0xFFA16207),
      darkColor: Color(0xFFFACC15),
    ),
    BlockShape(
      id: 't_down',
      label: 'T down',
      cells: [
        BlockPosition(0, 1),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(1, 2),
      ],
      lightColor: Color(0xFF854D0E),
      darkColor: Color(0xFFFDE047),
    ),
    BlockShape(
      id: 't_left',
      label: 'T left',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(2, 0),
      ],
      lightColor: Color(0xFF92400E),
      darkColor: Color(0xFFFCD34D),
    ),
    BlockShape(
      id: 't_right',
      label: 'T right',
      cells: [
        BlockPosition(0, 1),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(2, 1),
      ],
      lightColor: Color(0xFF78350F),
      darkColor: Color(0xFFFDE68A),
    ),
    BlockShape(
      id: 's_h',
      label: 'S horizontal',
      cells: [
        BlockPosition(0, 1),
        BlockPosition(0, 2),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
      ],
      lightColor: Color(0xFF15803D),
      darkColor: Color(0xFF86EFAC),
    ),
    BlockShape(
      id: 's_v',
      label: 'S vertical',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(2, 1),
      ],
      lightColor: Color(0xFF166534),
      darkColor: Color(0xFFBBF7D0),
    ),
    BlockShape(
      id: 'z_h',
      label: 'Z horizontal',
      cells: [
        BlockPosition(0, 0),
        BlockPosition(0, 1),
        BlockPosition(1, 1),
        BlockPosition(1, 2),
      ],
      lightColor: Color(0xFF0F766E),
      darkColor: Color(0xFF99F6E4),
    ),
    BlockShape(
      id: 'z_v',
      label: 'Z vertical',
      cells: [
        BlockPosition(0, 1),
        BlockPosition(1, 0),
        BlockPosition(1, 1),
        BlockPosition(2, 0),
      ],
      lightColor: Color(0xFF115E59),
      darkColor: Color(0xFFCCFBF1),
    ),
  ];
}
